# Generated by Django 4.2.6 on 2024-03-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=200, null=True)),
                ('number_of_tyres', models.CharField(blank=True, max_length=500, null=True)),
                ('size', models.CharField(blank=True, max_length=200, null=True)),
                ('design', models.CharField(blank=True, max_length=500, null=True)),
                ('LI_SI_PR', models.CharField(blank=True, max_length=500, null=True)),
                ('type', models.CharField(blank=True, max_length=200, null=True)),
                ('cat_no', models.CharField(blank=True, max_length=200, null=True)),
                ('tyre_serial_number', models.CharField(blank=True, max_length=200, null=True)),
                ('plant', models.CharField(blank=True, max_length=500, null=True)),
                ('claim_no', models.CharField(blank=True, max_length=200, null=True)),
                ('date_of_mounting', models.CharField(blank=True, max_length=200, null=True)),
                ('invoice_details', models.CharField(blank=True, max_length=500, null=True)),
                ('remaining_tread_depth', models.CharField(blank=True, max_length=200, null=True)),
                ('defect', models.CharField(blank=True, max_length=500, null=True)),
                ('our_recommendation', models.CharField(blank=True, max_length=200, null=True)),
                ('remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('dispose_by', models.CharField(blank=True, max_length=500, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=500, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_ref_no', models.CharField(blank=True, max_length=500, null=True)),
                ('ND_Used', models.CharField(blank=True, max_length=200, null=True)),
                ('old_ticket_no', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=300)),
                ('status', models.CharField(max_length=100)),
                ('complete_json', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('region', models.CharField(blank=True, max_length=500, null=True)),
                ('account_group', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('customer', models.CharField(blank=True, max_length=500, null=True)),
                ('search_term', models.CharField(blank=True, max_length=500, null=True)),
                ('street', models.CharField(blank=True, max_length=500, null=True)),
                ('house_number', models.CharField(blank=True, max_length=200, null=True)),
                ('street_2', models.CharField(blank=True, max_length=500, null=True)),
                ('street_3', models.CharField(blank=True, max_length=200, null=True)),
                ('street_4', models.CharField(blank=True, max_length=500, null=True)),
                ('street_5', models.CharField(blank=True, max_length=500, null=True)),
                ('city', models.CharField(blank=True, max_length=500, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=500, null=True)),
                ('country', models.CharField(blank=True, max_length=500, null=True)),
                ('branch', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ids', models.CharField(max_length=200)),
                ('customer_number', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=300)),
                ('status', models.CharField(max_length=100)),
                ('complete_json', models.CharField(max_length=500)),
            ],
        ),
    ]
