# Generated by Django 4.2.6 on 2024-03-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermapping',
            name='customer_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usermapping',
            name='user_ids',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
