# Generated by Django 4.2.6 on 2024-01-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='customer_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='customer_ref_no',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
