# Generated by Django 4.2.6 on 2024-03-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_usermapping_customer_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_value', models.CharField(blank=True, max_length=200, null=True)),
                ('size_value', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
