# Generated by Django 4.2.6 on 2024-03-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_excelsize'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, max_length=300, null=True)),
                ('date', models.CharField(blank=True, max_length=300, null=True)),
                ('no_of_tyre', models.CharField(blank=True, max_length=300, null=True)),
                ('size', models.CharField(blank=True, max_length=300, null=True)),
                ('design', models.CharField(blank=True, max_length=300, null=True)),
                ('li_si_pr', models.CharField(blank=True, max_length=300, null=True)),
                ('type', models.CharField(blank=True, max_length=300, null=True)),
                ('cat_no', models.CharField(blank=True, max_length=300, null=True)),
                ('tyre_serial_no', models.CharField(blank=True, max_length=300, null=True)),
                ('plant', models.CharField(blank=True, max_length=300, null=True)),
                ('claim_no', models.CharField(blank=True, max_length=300, null=True)),
                ('date_of_invoice', models.CharField(blank=True, max_length=300, null=True)),
                ('invoice_details', models.CharField(blank=True, max_length=300, null=True)),
                ('remaining_tread_depth', models.CharField(blank=True, max_length=300, null=True)),
                ('defect_code_description', models.CharField(blank=True, max_length=300, null=True)),
                ('our_recommendation', models.CharField(blank=True, max_length=300, null=True)),
                ('remarks', models.CharField(blank=True, max_length=300, null=True)),
                ('disposed_by', models.CharField(blank=True, max_length=300, null=True)),
                ('customer_code', models.CharField(blank=True, max_length=300, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=300, null=True)),
                ('country_working', models.CharField(blank=True, max_length=300, null=True)),
                ('region', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
