# Generated by Django 4.2.6 on 2024-03-14 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_customerticket_excel_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerticket',
            name='mapsize',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='customerticket',
            name='requester_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
