# Generated by Django 4.2.6 on 2024-03-14 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_customerticket_mapsize_customerticket_requester_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignLISIMAP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapdesign', models.CharField(blank=True, max_length=300, null=True)),
                ('excel_design', models.CharField(blank=True, max_length=300, null=True)),
                ('map_li_si_pr', models.CharField(blank=True, max_length=300, null=True)),
                ('excel_li_si', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
