# Generated by Django 4.2.6 on 2024-03-14 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_designlisimap_excel_li_si_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LI_SI_PRMAP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_li_si_pr', models.CharField(blank=True, max_length=300, null=True)),
                ('excel_li_si', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
