# Generated by Django 4.2.6 on 2024-03-14 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_li_si_prmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerticket',
            name='map_design',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='customerticket',
            name='map_li_si_pr',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
