# Generated by Django 4.2.6 on 2024-04-01 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_defect_code_customerticket_map_defect_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fakeuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('email', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
