# Generated by Django 4.2.6 on 2024-04-19 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_fakeuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket_ids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_ids', models.CharField(blank=True, max_length=300, null=True)),
                ('claims', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
