# Generated by Django 4.2.6 on 2024-04-24 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_ticket_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerticket',
            name='excel_size',
        ),
        migrations.RemoveField(
            model_name='customerticket',
            name='user_mapping',
        ),
    ]
